### ISSUE TITLE
Rename application.es6 to application.js

### ISSUE THREAD

**Issue by louis-vs** [jmalcic/spina-admin-conferences#281]
File /app/assets/javascripts/spina/admin/conferences/application.es6 needs to be renamed to .js in order to be picked up correctly by the asset pipeline ([see docs](https://apidock.com/rails/v6.0.0/ActionView/Helpers/AssetTagHelper/javascript_include_tag)). This is relevant for the javascript_include_tag in /app/views/spina/admin/hooks/conferences/_head.html.haml.

This is at the least a compatibility issue for the ulab-committee-website, clone commit [0d6d56d](https://github.com/ulab-committee/ulab-website/commit/0d6d56dfb3a44b11f180745967fa30ac8ce157ac) to try for yourself.

**Comment by jmalcic** [comment]
This should be fixed by 923903f5427bedc1515798e30db46a305bfc465e. These files will be available through Sprockets instead.
